window.liveData = [
{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '', unit: 'U2', gps: '🟢 A TIEMPO', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #2)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '00:00', unit: 'U1', gps: '🟡 RETRASO LEVE', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #1)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '00:30', unit: 'U1', gps: '🔴 CRÍTICO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Abasto (Preventa)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '05:15', unit: 'U1', gps: 'TOTAL VIAJES', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '05:45', unit: 'U1', gps: '% EFICIENCIA', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '10:15', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #1)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #4)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '23', time: '03:05', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:15', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '23', time: '10:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:05', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '23', time: '13:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '23', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '24', time: '07:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '24', time: '10:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '24', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '24', time: '16:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '24', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '25', time: '07:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '25', time: '10:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '25', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '25', time: '16:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '25', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '26', time: '07:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '26', time: '10:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '26', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '26', time: '16:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '26', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '27', time: '03:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '27', time: '07:25', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '27', time: '11:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '27', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '27', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '28', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '28', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '28', time: '21:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '21:15', unit: 'U1', gps: '🟢 A TIEMPO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '00:00', unit: 'U2', gps: '🟡 RETRASO LEVE', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '03:00', unit: 'U1', gps: '🔴 CRÍTICO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '03:30', unit: 'U1', gps: 'TOTAL VIAJES', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '10:15', unit: 'U1', gps: '% EFICIENCIA', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '23', time: '04:05', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '23', time: '07:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'TRÁNSITO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '23', time: '11:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'TRÁNSITO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '23', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '24', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '24', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '24', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '24', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '24', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '25', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '25', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '25', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '25', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '25', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '26', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '26', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '26', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '26', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '26', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '27', time: '05:25', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '27', time: '05:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '27', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '27', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '27', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '28', time: '07:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '28', time: '10:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '28', time: '22:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '21:15', unit: 'U1', gps: '🟢 A TIEMPO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '00:00', unit: 'U2', gps: '🟡 RETRASO LEVE', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '03:00', unit: 'U1', gps: '🔴 CRÍTICO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '03:30', unit: 'U1', gps: 'TOTAL VIAJES', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '10:15', unit: 'U1', gps: '% EFICIENCIA', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '23', time: '04:05', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '23', time: '07:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'TRÁNSITO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '23', time: '11:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'TRÁNSITO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '23', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '24', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '24', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '24', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '24', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '24', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '25', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '25', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '25', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '25', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '25', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '26', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '26', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '26', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '26', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '26', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '27', time: '05:25', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '27', time: '05:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '27', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '27', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '27', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '28', time: '07:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '28', time: '10:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '28', time: '22:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
];
