window.liveData = [
{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '', unit: 'U2', gps: '🟢 A TIEMPO', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #2)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '00:00', unit: 'U1', gps: '🟡 RETRASO LEVE', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #1)', route: 'Z12 → CD', detail: '13:45', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '00:30', unit: 'U1', gps: '🔴 CRÍTICO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Abasto (Preventa)', route: 'CD → Z12', detail: '11:42', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '05:15', unit: 'U1', gps: 'TOTAL VIAJES', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #2)', route: 'Z12 → CD', detail: '07:33', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '05:45', unit: 'U1', gps: '% EFICIENCIA', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Mat. Prima', route: 'CD → Z12', detail: '08:37', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '10:15', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #1)', route: 'ANT → CD', detail: '04:38', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '5', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #4)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #2)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #1)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Abasto (Preventa)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #1)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '6', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #4)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #2)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #1)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Abasto (Preventa)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #1)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '7', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #4)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #2)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #1)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Abasto (Preventa)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '05:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Mat. Prima', route: 'CD → Z12', detail: '13:06', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '10:15', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #1)', route: 'ANT → CD', detail: '08:36', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '12:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #3)', route: 'Z12 → CD', detail: '06:51', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '8', time: '15:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #4)', route: 'Z12 → CD', detail: '03:21', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #2)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #1)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Abasto (Preventa)', route: 'CD → Z12', detail: '00:00', cause: 'Trafico pesado', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #2)', route: 'Z12 → CD', detail: '00:00', cause: 'Bloqueo accidente_____________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #1)', route: 'ANT → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '9', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #4)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #2)', route: 'ANT → CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #1)', route: 'Z12 → CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Abasto (Preventa)', route: 'CD → Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #2)', route: 'Z12 → CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Carga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '⚡ Descarga PT (Ant #1)', route: 'ANT → CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #3)', route: 'Z12 → CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Febrero', day: '10', time: '', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '⚡ Descarga PT (Z12 #4)', route: 'Z12 → CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '9', time: '02:05', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '06:45', cause: '', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '9', time: '10:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '9', time: '13:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '9', time: '16:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '9', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '9', time: '00:15', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '10', time: '02:05', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '10', time: '10:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '10', time: '13:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '10', time: '16:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '10', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '10', time: '00:15', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '03:25', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '06:35', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '07:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '10:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '16:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '11', time: '00:15', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT NOCHE Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '12', time: '03:25', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '12', time: '03:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '12', time: '10:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '12', time: '13:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '12', time: '16:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '12', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '13', time: '02:05', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '13', time: '10:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '13', time: '13:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '13', time: '16:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '13', time: '23:50', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '13', time: '00:15', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '14', time: '03:25', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '14', time: '21:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '14', time: '00:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '15', time: '03:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '15', time: '04:10', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '15', time: '06:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '15', time: '07:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'CD BÁRCENAS', month: 'Marzo', day: '15', time: '10:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '21:15', unit: 'U1', gps: '🟢 A TIEMPO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '00:00', unit: 'U2', gps: '🟡 RETRASO LEVE', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '13:45', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '03:00', unit: 'U1', gps: '🔴 CRÍTICO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '09:12', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '03:30', unit: 'U1', gps: 'TOTAL VIAJES', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '09:18', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '10:15', unit: 'U1', gps: '% EFICIENCIA', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '5', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '6', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '6', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '6', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '6', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '6', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '6', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '6', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '7', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '7', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '7', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '7', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '7', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '7', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '7', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '8', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '8', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '8', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '8', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '8', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '8', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '8', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '9', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '9', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '09:19', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '9', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '9', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '9', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '9', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '9', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '10', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '10', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '10', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '10', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '10', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '10', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Febrero', day: '10', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '9', time: '03:40', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '9', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '9', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '9', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '9', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '10', time: '03:40', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '10', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '10', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '10', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '10', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '10', time: '22:40', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '01:50', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '05:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '11', time: '22:40', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '12', time: '01:50', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '12', time: '05:25', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '12', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '12', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '12', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '12', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '13', time: '03:40', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '13', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '13', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '13', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '13', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '13', time: '22:40', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '14', time: '01:50', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '14', time: '22:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '14', time: '23:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '15', time: '02:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '15', time: '02:35', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '15', time: '05:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '15', time: '08:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ZONA 12', month: 'Marzo', day: '15', time: '09:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '21:15', unit: 'U1', gps: '🟢 A TIEMPO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '00:00', unit: 'U2', gps: '🟡 RETRASO LEVE', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '13:45', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '03:00', unit: 'U1', gps: '🔴 CRÍTICO', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '09:12', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '03:30', unit: 'U1', gps: 'TOTAL VIAJES', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '09:18', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '10:15', unit: 'U1', gps: '% EFICIENCIA', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '5', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '6', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '6', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '6', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '6', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '6', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '6', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '6', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '7', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '7', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '7', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '7', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '7', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '7', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '7', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '8', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '8', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '8', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '8', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '8', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '8', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '8', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '9', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '9', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '09:19', cause: '__________________', statusText: 'EN PATIO', statusClass: 'status-alert'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '9', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '9', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '9', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '9', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '9', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '10', time: '21:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V1)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '10', time: '00:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: '🔵 Inicio Carga Masas', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '10', time: '03:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Abasto', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '10', time: '03:30', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V2)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '10', time: '10:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟢 Descarga Mat. Prima', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '10', time: '10:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V3)', route: 'Z12 → CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Febrero', day: '10', time: '13:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: '🟡 Inicio Carga PT (V4)', route: 'CD → Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '9', time: '03:40', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '9', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '9', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '9', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '9', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '10', time: '03:40', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '10', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '__________________', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '10', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '10', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '10', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '10', time: '22:40', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '01:50', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '05:00', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '09:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '12:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '15:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '11', time: '22:40', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '12', time: '01:50', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '12', time: '05:25', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '12', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '12', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '12', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '12', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '13', time: '03:40', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '13', time: '08:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '13', time: '11:45', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MAÑANA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '13', time: '14:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT TARDE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '13', time: '22:15', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT NOCHE', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '13', time: '22:40', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '14', time: '01:50', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT EXTRA Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '14', time: '22:35', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '14', time: '23:00', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '15', time: '02:10', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '15', time: '02:35', unit: 'U2', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-868CBJ', pilot: 'Eliu Terron', phone: '55614584', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '15', time: '05:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT SÁBADO Z12', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '15', time: '08:55', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'Carga Abasto (Preventa)', route: 'CD -> Z12', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
,{location: 'FÁBRICA ANTIGUA', month: 'Marzo', day: '15', time: '09:20', unit: 'U1', gps: 'https://www.google.com/maps/place/Nestl%C3%A9+Guatemala', plate: 'C-816CCD', pilot: 'Orlando Terron', phone: '56118481', mission: 'PT MADRUGADA', route: 'Z12 -> CD', detail: '00:00', cause: '', statusText: 'PROGRAMADO', statusClass: 'status-pending'}
];
